# Booknames Frequency
This notebook looks at the top comments of each of the Worship Service Examination threads on r/exIglesiaNiCristo and returns the frequencies of each bookname from the bible.

In [24]:
import pandas as pd

all_comments_df = pd.read_csv(r"https://raw.githubusercontent.com/anxiousasallhelll/exINCult/main/Worship_Service_Examination_All_Comments.csv")
all_comments_df

,Post_Title,Post_ID,Post_Date,Comment,Post_URL
0,Mid-week worship service examination (Apr 10 -...,bblvt0,2019-04-10,"The usual, do not leave the church stuff. Obey...",https://www.reddit.com/r/exIglesiaNiCristo/com...
1,Mid-week worship service examination (Apr 10 -...,bblvt0,2019-04-10,Todayâ€™s lesson was definitely â€œDonâ€™t leave the...,https://www.reddit.com/r/exIglesiaNiCristo/com...
2,Mid-week worship service examination (Apr 10 -...,bblvt0,2019-04-10,Lesson this week was about uphold fervour till...,https://www.reddit.com/r/exIglesiaNiCristo/com...
3,Mid-week worship service examination (Apr 10 -...,bblvt0,2019-04-10,"To summarize it up, it's about serving God or ...",https://www.reddit.com/r/exIglesiaNiCristo/com...
4,Mid-week worship service examination (Apr 10 -...,bblvt0,2019-04-10,Thank you for sharing. I wonder on how long w...,https://www.reddit.com/r/exIglesiaNiCristo/com...
...,...,...,...,...,...
5000,Weekend Worship Service Examination (Jul 22 - ...,w5bck2,2022-07-22,Boring indeed,https://www.reddit.com/r/exIglesiaNiCristo/com...
5001,Weekend Worship Service Examination (Jul 22 - ...,w5bck2,2022-07-22,I even nearly forgot that I was in an INC than...,https://www.reddit.com/r/exIglesiaNiCristo/com...
5002,Weekend Worship Service Examination (Jul 22 - ...,w5bck2,2022-07-22,Ohhh okay. Central already holded a TG led by ...,https://www.reddit.com/r/exIglesiaNiCristo/com...
5003,Weekend Worship Service Examination (Jul 22 - ...,w5bck2,2022-07-22,"It is not like telling a lie, it is a lie.",https://www.reddit.com/r/exIglesiaNiCristo/com...
5004,Weekend Worship Service Examination (Jul 22 - ...,w5bck2,2022-07-22,LOL ðŸ˜‚,https://www.reddit.com/r/exIglesiaNiCristo/com...

In [25]:
top_comments_df = pd.read_csv(r"https://raw.githubusercontent.com/anxiousasallhelll/exINCult/main/Worship_Service_Examination_Top_Comments.csv")
top_comments_df

,Post_Title,Post_ID,Post_Date,Comment,Post_URL
0,Mid-week worship service examination (Apr 10 -...,bblvt0,2019-04-10,"The usual, do not leave the church stuff. Obey...",https://www.reddit.com/r/exIglesiaNiCristo/com...
1,Mid-week worship service examination (Apr 10 -...,bblvt0,2019-04-10,Todayâ€™s lesson was definitely â€œDonâ€™t leave the...,https://www.reddit.com/r/exIglesiaNiCristo/com...
2,Mid-week worship service examination (Apr 10 -...,bblvt0,2019-04-10,Lesson this week was about uphold fervour till...,https://www.reddit.com/r/exIglesiaNiCristo/com...
3,Mid-week worship service examination (Apr 10 -...,bblvt0,2019-04-10,"To summarize it up, it's about serving God or ...",https://www.reddit.com/r/exIglesiaNiCristo/com...
4,Mid-week worship service examination (Sep 04 -...,czkqez,2019-09-04,"Same thing as every week. It started off with,...",https://www.reddit.com/r/exIglesiaNiCristo/com...
...,...,...,...,...,...
1787,Weekend Worship Service Examination (Jul 22 - ...,w5bck2,2022-07-22,It felt like I just attended a bible study ðŸ¥´,https://www.reddit.com/r/exIglesiaNiCristo/com...
1788,Weekend Worship Service Examination (Jul 22 - ...,w5bck2,2022-07-22,so i'm trying not to get in trouble so let me ...,https://www.reddit.com/r/exIglesiaNiCristo/com...
1789,Weekend Worship Service Examination (Jul 22 - ...,w5bck2,2022-07-22,Poor members. They work really hard to make bo...,https://www.reddit.com/r/exIglesiaNiCristo/com...
1790,Weekend Worship Service Examination (Jul 22 - ...,w5bck2,2022-07-22,PPV?,https://www.reddit.com/r/exIglesiaNiCristo/com...
1791,Weekend Worship Service Examination (Jul 22 - ...,w5bck2,2022-07-22,Pasalamat kanina and yung lesson namin kanina ...,https://www.reddit.com/r/exIglesiaNiCristo/com...

In [26]:
bible_books_df = pd.read_csv("https://raw.githubusercontent.com/jpoehls/bible-metadata/master/Books.csv")
bible_books_df

    BookID OsisID     BookName  TotalChapters Volume
0        1    Gen      Genesis             50     OT
1        2   Exod       Exodus             40     OT
2        3    Lev    Leviticus             27     OT
3        4    Num      Numbers             36     OT
4        5   Deut  Deuteronomy             34     OT
..     ...    ...          ...            ...    ...
61      62  1John       1 John              5     NT
62      63  2John       2 John              1     NT
63      64  3John       3 John              1     NT
64      65   Jude         Jude              1     NT
65      66    Rev   Revelation             22     NT

[66 rows x 5 columns]

In [27]:
booknames_freq_from_comments_dict = dict.fromkeys(bible_books_df['BookName'], 0)
booknames_comments = dict.fromkeys(bible_books_df['BookName'], [])
booknames = bible_books_df['BookName']
for comment in top_comments_df['Comment']:
    for bookname in booknames:
        if bookname in comment:
            booknames_freq_from_comments_dict[bookname] += 1

booknames_freq_from_comments_dict

{'Genesis': 16,
 'Exodus': 5,
 'Leviticus': 2,
 'Numbers': 3,
 'Deuteronomy': 19,
 'Joshua': 2,
 'Judges': 2,
 'Ruth': 0,
 '1 Samuel': 5,
 '2 Samuel': 3,
 '1 Kings': 2,
 '2 Kings': 2,
 '1 Chronicles': 3,
 '2 Chronicles': 3,
 'Ezra': 0,
 'Nehemiah': 2,
 'Esther': 0,
 'Job': 20,
 'Psalms': 39,
 'Proverbs': 23,
 'Ecclesiastes': 9,
 'Song of Solomon': 0,
 'Isaiah': 52,
 'Jeremiah': 14,
 'Lamentations': 2,
 'Ezekiel': 4,
 'Daniel': 4,
 'Hosea': 2,
 'Joel': 3,
 'Amos': 0,
 'Obadiah': 0,
 'Jonah': 0,
 'Micah': 2,
 'Nahum': 0,
 'Habakkuk': 2,
 'Zephaniah': 2,
 'Haggai': 3,
 'Zechariah': 1,
 'Malachi': 3,
 'Matthew': 55,
 'Mark': 16,
 'Luke': 29,
 'John': 78,
 'Acts': 110,
 'Romans': 54,
 '1 Corinthians': 23,
 '2 Corinthians': 27,
 'Galatians': 13,
 'Ephesians': 41,
 'Philippians': 32,
 'Colossians': 30,
 '1 Thessalonians': 7,
 '2 Thessalonians': 6,
 '1 Timothy': 6,
 '2 Timothy': 7,
 'Titus': 6,
 'Philemon': 1,
 'Hebrews': 60,
 'James': 35,
 '1 Peter': 14,
 '2 Peter': 6,
 '1 John': 14,
 '2 John': 0,
 '3 John': 0,
 'Jude': 10,
 'Revelation': 32}

In [31]:
booknames_freq_from_comments_df = pd.DataFrame.from_dict(booknames_freq_from_comments_dict, orient='index', columns= ['Freq'])
booknames_freq_from_comments_df.sort_values(by='Freq', ascending=False)

                 Freq
Acts              110
John               78
Hebrews            60
Matthew            55
Romans             54
...               ...
Song of Solomon     0
2 John              0
3 John              0
Esther              0
Nahum               0

[66 rows x 1 columns]